### ISSUE TITLE
Display the status Connection for the cluster

### ISSUE THREAD

**Issue by smartx-usman** [OFTEIN-NET/OFTEIN-MultiTenantPortal#2]
Make a mechanism to Display the status Connection for the cluster and regularly check.

**Comment by ariscahyadi** [comment]
Just random ideas, I think we can use this API command to check the cluster status https://kubernetes.io/docs/reference/using-api/health-checks/

Then, we have two options for the tenant to select:
* Show the status of the cluster, so they can't select the "down" cluster
* Make dropdown list only for "up" cluster

What do you think @smartx-usman ?

**Comment by smartx-usman** [comment]
Idea seems feasible. I am in favor of first option to show the status of all clusters and let the tenant select cluster that is up.

**Comment by ariscahyadi** [comment]
Ok... but first we need @NattVi and Chula team to add https://kubernetes.io/docs/reference/using-api/health-checks/ in their backend implementation.

**Comment by ariscahyadi** [comment]
@smartx-usman @NattVi @benzkittipat can we use this API `http://<server_name>:<port>/clusters/<cluster_name>` to check the cluster status?

**Comment by smartx-usman** [comment]
I am already working on this aspect (able to get cluster info) and changes are in above linked PR.
