### ISSUE TITLE
Connect frontend with backend API server

### ISSUE THREAD

**Issue by smartx-usman** [OFTEIN-NET/OFTEIN-MultiTenantPortal#3]
Chula site has developed backend resources that should be called from frontend.

**Comment by ariscahyadi** [comment]
@NattVi and Kittipat already has develop API call for Pod, we just need to put in the GitHub.
But, do we need something like "bootstrap" or "init" script to run both front end and back end together @smartx-usman?

**Comment by smartx-usman** [comment]
The front end application is going to be docker image, so it should be running persistently. We may have init script or some default mechanism from docker to make sure it is running.

**Comment by ariscahyadi** [comment]
> The front end application is going to be docker image, so it should be running persistently. We may have init script or some default mechanism from docker to make sure it is running.

Shall we make back-end and front-end into Docker images, so we can initialize both of them using Docker Compose?

**Comment by smartx-usman** [comment]
> > The front end application is going to be docker image, so it should be running persistently. We may have init script or some default mechanism from docker to make sure it is running.
> 
> Shall we make back-end and front-end into Docker images, so we can initialize both of them using Docker Compose?

Yes, we should go in this direction because I don’t see any issue in dockerizing back-end as well. But again depends on back-end application developers to agree upon.

**Comment by ariscahyadi** [comment]
> > > The front end application is going to be docker image, so it should be running persistently. We may have init script or some default mechanism from docker to make sure it is running.
> > 
> > 
> > Shall we make back-end and front-end into Docker images, so we can initialize both of them using Docker Compose?
> 
> Yes, we should go in this direction because I don’t see any issue in dockerizing back-end as well. But again depends on back-end application developers to agree upon.

Agree... let's wait @NattVi to response to this issue.

**Comment by NattVi** [comment]
https://github.com/OFTEIN-NET/OFTEIN-MultiTenantPortal/tree/main/backend-app 

we updated backend resources and list all the api

**Comment by smartx-usman** [comment]
> https://github.com/OFTEIN-NET/OFTEIN-MultiTenantPortal/tree/main/backend-app
> 
> we updated backend resources and list all the api

Thanks @NattVi.

**Comment by ariscahyadi** [comment]
@smartx-usman and @NattVi I think we can close this issue and continue working with this issue #7, right?

**Comment by smartx-usman** [comment]
@ariscahyadi let these two issues stay separately for time being. This one is more of implementation issue while #7 is deployment issue.
