### ISSUE TITLE
Create backend App Docker image via GitHub Actions

### ISSUE THREAD

**Issue by smartx-usman** [OFTEIN-NET/OFTEIN-MultiTenantPortal#6]
- Add a GitHub action for building Docker image
- Push Docker image to image registry via GitHub action

**Comment by ariscahyadi** [comment]
@smartx-usman will it push to DockerHub or some other repository?

**Comment by smartx-usman** [comment]
> @smartx-usman will it push to DockerHub or some other repository?

I prefer dockerhub. I push frontend app docker image to dockerhub as well.
